version: "3"
services:
  testdb:
    image: postgres
    restart: always
    container_name: grafitty_place_db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=postgres"
    ports:
      - 44444:5432